
services:
  app:
    image: phone-front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: phone-front

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-phone-prod
    depends_on:
      - app
      - server

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./backend/mongo_data:/data/db

  server:
    image: phone-back
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phone-back
    environment:
      MONGODB_URI: mongodb://the_username:the_password@mongo:27017/the_database
      PORT: 3000
