
services:
  app:
    image: phone-front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend:/usr/src/app:rw
    container_name: phone-front-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-phone-dev
    depends_on:
      - app
      - server

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo_data:/data/db
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  server:
    image: phone-back-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app:rw
    container_name: phone-back-dev
    environment:
      MONGODB_URI: mongodb://the_username:the_password@mongo:27017/the_database
      PORT: 3000
